#=================================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK/Cath
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: 0 20 * * *
jobs:
   build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede lede

    - name: enable magic
      run: cd lede && echo 'src-git helloworld https://github.com/fw876/helloworld'>>./feeds.conf.default
    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cp -f gdockfull128.config ./lede/.config
        chmod +x diy.sh
        cd lede
        ../diy.sh
        make defconfig

    - name: Download package
      run: |
        echo -e "$(nproc) thread build."
        cd lede && make download -j$(nproc)

    - name: Build
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        rm -rf ./bin/targets/ipq40xx/generic/packages

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: G-DOCK
        path: ./lede/bin/targets/ipq40xx/generic/
